services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nevroth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  api:
    build: .
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_started

  celery:
    build: .
    command: celery -A nevroth worker --loglevel=info
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started

  celery-beat:
    build: .
    command: celery -A nevroth beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      celery:
        condition: service_started

  flower:
    image: mher/flower:latest
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/2
    depends_on:
      - redis

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DISABLE_CORS_CHECKS=1
      - DATA_DIR=/var/lib/localstack/data
    ports:
      - "4566:4566"
    volumes:
      - ./localstack-init:/etc/localstack/init/ready.d
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  localstack_data: