# Generated by Django 5.2.3 on 2025-07-01 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habitprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='habitprogress',
            index=models.Index(fields=['user', 'habit', 'date'], name='habits_habi_user_id_a6243a_idx'),
        ),
    ]
