# Generated by Django 5.2.3 on 2025-07-08 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendsRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                            ("pending", "pending"),
                        ],
                        default="pending",
                        max_length=8,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="from user",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="to user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["from_user"], name="friends_fri_from_us_867a52_idx"
                    ),
                    models.Index(
                        fields=["to_user"], name="friends_fri_to_user_86759a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="friends_fri_status_bd3d26_idx"
                    ),
                ],
                "unique_together": {("from_user", "to_user")},
            },
        ),
    ]
